services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  mysql:
    image: mysql
    container_name: mysql-gorm
    environment:
      MYSQL_ROOT_PASSWORD: "1234" # Root password
      MYSQL_DATABASE: "gorm_db"   # Default database
    ports:
      - "3306:3306"
    volumes:
      - ./back/mysql_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80" # Map Nginx to host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
